function onCreatePost()
	setTextFont("timeTxt", "gameboy.ttf")
	setTextSize("timeTxt", 24)
	setTextFont("botplayTxt", "gameboy.ttf")
	setTextSize("botplayTxt", 24)
	setProperty("botplayTxt.x", getProperty("botplayTxt.x") - 8)
	setTextFont("scoreTxt", "smb1.ttf")
	setTextSize("scoreTxt", 16)

	setTextColor("scoreBar", "0xFF9BBC0F")
	setTextFont("scoreBar", "gameboy.ttf")
	setTextColor("accuracyText", "0xFF9BBC0F")
	setTextFont("accuracyText", "gameboy.ttf")
	setTextColor("accuracyText2", "0xFF9BBC0F")
	setTextColor("timeTxt", "0xFF9BBC0F")
	setTextBorder("timeTxt", 2, "0f380f")
	setTextColor("botplayTxt", "0xFF9BBC0F")
	setTextBorder("botplayTxt", 2, "0f380f")
	setTextColor("scoreTxt", "0xFF9BBC0F")
	setTextBorder("scoreTxt", 2, "0f380f")

	setProperty("timeBarBG.visible", false)
	setProperty("timeBar.visible", false)
	loadGraphic("healthBarBG", "healthBar-gameboy")

	setTextFont('JukeBoxText', 'gameboy.ttf')
	setTextColor("JukeBoxText", "0xFF9BBC0F")
	setTextBorder("JukeBoxText", 2, "0f380f")
	setTextFont('JukeBoxSubText', 'gameboy.ttf')
	setTextColor("JukeBoxSubText", "0xFF9BBC0F")
	setTextBorder("JukeBoxSubText", 2, "0f380f")
end